[package]
name = "deimos"
version = "0.1.0"
authors = ["Ash <ext0l@catgirl.ai>"]
edition = "2021"
homepage = "http://github.com/deifactor/deimos"
repository = "http://github.com/deifactor/deimos"

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
crossbeam = "0.8.2"
cursive = "0.20.0"
rodio = { version = "0.17.1", default-features = false, features = ["symphonia-all"] }
sqlx = { version = "0.6", features = ["sqlite", "runtime-tokio-native-tls"] }
symphonia = { version = "0.5.3", features = ["all"] }
tokio = { version = "1.28.2", features = ["full"] }
walkdir = "2.3.3"
