literal = {(!("$" | "%" | "{" | "}") ~ ANY)+}

identifier = {ASCII_ALPHANUMERIC+}
variable = {"$" ~ identifier}

color = _{ ^"red" | ^"black" | ^"white" }
fg_color = { color }
attribute = _{ fg_color }
separator = _{ "," ~ " "* }
style = { " "* ~ attribute ~ ("," ~ " "* ~ attribute)* ~ " "* }
styled = { "%[" ~ style ~ "]{" ~ format_string ~ "}" }

format_string = _{ (literal | variable | styled)+ }
format_string_entire = _{ SOI ~ format_string ~ EOI }
